# work flow name user-profile

name: "user-profile"
# workflow run on pull or push to master
on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master

# jobs to run on sequentially or parallel
jobs:

# setup node environment
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        registry-url: https://registry.npmjs.org
    - run: npm install

# unit test
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

# test case
#  test:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: action/checkout@v2
#    - run: ./
#      with:
#        milliseconds: 1000

# eslint
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        registry-url: https://registry.npmjs.org
    - run: npm ci
    - run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        registry-url: https://registry.npmjs.org
    - run: npm ci
    - run: npm run build

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: npm ci
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS creds directly
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}